# Generated by Django 4.2 on 2023-05-03 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0003_alter_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requesting', 'Requesting'), ('accepted', 'Accepted'), ('denied', 'Denied'), ('borrowed', 'Borrowed'), ('due', 'Due'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='requesting', max_length=20)),
                ('date_requested', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_accepted', models.DateTimeField(blank=True, null=True)),
                ('date_borrowed', models.DateTimeField(blank=True, null=True)),
                ('date_due', models.DateTimeField(blank=True, null=True)),
                ('date_returned', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
