# Generated by Django 4.2 on 2023-05-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='date_cancelled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='date_denied',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
