# Generated by Django 4.2 on 2023-05-04 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_borrowrequest_date_cancelled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'TransactionStatuses',
            },
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='status',
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='date_accepted',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='date_borrowed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='date_cancelled',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='date_denied',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='date_due',
            field=models.DateTimeField(blank=True, help_text='Date for due', null=True),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='date_requested',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='date_returned',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='transactionstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactionstatus', to='transactions.transactionstatus'),
        ),
    ]
