# Generated by Django 4.2 on 2023-05-04 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transactionstatus_remove_borrowrequest_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrequest',
            name='date_accepted',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='date_borrowed',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='date_cancelled',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='date_denied',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='date_due',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='date_requested',
        ),
    ]
