# Generated by Django 4.2 on 2023-05-07 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_days_transaction_delete_borrowrequest_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Days',
            new_name='Day',
        ),
    ]
