# Generated by Django 4.2 on 2023-05-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_rename_days_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='book',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
